import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F2F2F7",
  },
  content: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F2F2F7",
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#8E8E93",
    fontWeight: "500",
  },
  statsContainer: {
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statNumber: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#007AFF",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 13,
    color: "#8E8E93",
    fontWeight: "500",
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
  },
  calendarSection: {
    marginHorizontal: 16,
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1C1C1E",
  },
  toggleIcon: {
    fontSize: 16,
    color: "#8E8E93",
  },
  calendarWrapper: {
    paddingHorizontal: 8,
    paddingBottom: 16,
  },
  calendar: {
    borderRadius: 12,
  },
  selectedDateSection: {
    marginHorizontal: 16,
    marginBottom: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  selectedDateHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  selectedDateTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1C1C1E",
    flex: 1,
  },
  clearButton: {
    fontSize: 14,
    color: "#007AFF",
    fontWeight: "600",
  },
  selectedTicketsList: {
    gap: 12,
  },
  noTicketsContainer: {
    padding: 32,
    alignItems: "center",
  },
  noTicketsText: {
    fontSize: 15,
    color: "#8E8E93",
    textAlign: "center",
  },
  kanbanSection: {
    marginTop: 8,
    paddingHorizontal: 16,
  },
  dragInstructions: {
    fontSize: 13,
    color: "#8E8E93",
    marginTop: 8,
    marginBottom: 16,
    textAlign: "center",
    fontStyle: "italic",
  },
  kanbanContainer: {
    gap: 16,
  },
  columnWrapper: {
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    marginBottom: 8,
  },
  columnHeader: {
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  columnIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  columnCount: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  columnTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1C1C1E",
    flex: 1,
  },
  dropZone: {
    minHeight: 120,
    paddingVertical: 8,
  },
  columnScroll: {
    maxHeight: 400,
  },
  columnContent: {
    padding: 12,
    gap: 12,
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    borderLeftWidth: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1C1C1E",
    flex: 1,
  },
  cardDescription: {
    fontSize: 13,
    color: "#8E8E93",
    lineHeight: 18,
    marginBottom: 12,
  },
  cardFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  assigneeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flex: 1,
  },
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#007AFF",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  assigneeText: {
    fontSize: 13,
    color: "#1C1C1E",
    fontWeight: "500",
    flex: 1,
  },
  dueDateText: {
    fontSize: 12,
    color: "#8E8E93",
    fontWeight: "500",
  },
  dragHint: {
    alignItems: "center",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F2F2F7",
  },
  dragHintText: {
    fontSize: 11,
    color: "#C7C7CC",
    fontStyle: "italic",
  },
  emptyContainer: {
    padding: 32,
    alignItems: "center",
  },
  emptyText: {
    fontSize: 14,
    color: "#C7C7CC",
    textAlign: "center",
    fontWeight: "500",
  },
  emptySubtext: {
    fontSize: 12,
    color: "#E5E5EA",
    textAlign: "center",
    marginTop: 4,
  },
});

export default styles;
